### ISSUE TITLE
IntChecker v2.5.0 + Far b4951 - не запускается операция Сравнение панелей

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#1]
Условия: Win7 SP1 x64, .Far b4951 NET 4.7, рунтаймы 2008 - 2017 есть, RAM 16 Gb (должно хватать)

Случайно увидел когда потребовалось сравнить пару каталогов по SHA-256 - выбрал, нажимаю Run (Запуск) операция не запускается. Правда есть червячок сумления - нет ли тут вины .NET 4.7? До его установки я сравнение каталогов проводил, но вероятно в 2.4.3, а та и сейчас работает.

И ещё, но это чисто косметическое - я посмотрел описание алгоритма SHA3 - там переменная длина хэша, у нас 512 бит, может сделать единообразно с SHA2-512? Мало ли потребуется и SHA3-256/384 добавить? Я бы заранее исключил путаницу, хотя по размеру хэша не сложно ориентироваться...

**Comment by lazyhamster** [comment]
Да, не работает кнопочка запуска. Исправил.

**Comment by VictorVG** [comment]
А какая версия буст-а нужна для сборки и куда её класть?

**Comment by lazyhamster** [comment]
По идее любая пойдет. Бери самую новую, не ошибешься. Последний релиз я на 1.63 собирал.

Класть можно куда угодно, в проекте путь к бусту не прописывался. Я его себе в студии прописал, чтобы на каждый проект не добавлять.

**Comment by VictorVG** [comment]
Ща у себя поищу. Где-то был на архивных винтах.

**Comment by lazyhamster** [comment]
Собрать его только надо. В плагине либа с регекспами используется, её билдить надо.

**Comment by VictorVG** [comment]
Скачал тут последнюю 1.64, а компилер  ругается на невключение файлов. Пытаюсь сообразить, но по сути я давно серьёзно не кодил и путаюсь....

**Comment by VictorVG** [comment]
Ничего с это буст не выходит то ей этого нет то компилятор не устраивает те ей подава пространства на сотню терабаайт. Озверел, стёр.

**Comment by VictorVG** [comment]
Не хочет у меня это полгиговое чудо собираться. То компилатор ему не тот, то исходника нет и где его взять не известно. Придётся ждать. Более идиотской либы даже в Коболе OS/360 известном своим "причудливыми" не видал. :(

**Comment by lazyhamster** [comment]
Хм. Скачал ради интереса 1.64. Всё собралось без проблем под 2013 студию.
И плагин с этой версией собрался нормально.

**Comment by VictorVG** [comment]
У меня она не доступна. 10. 15. 17 на сервере. А как паравильно эту либу собрать?

**Comment by lazyhamster** [comment]
Сначала bootstrap.bat. Потом запускать b2 с параметрами (bootstrap.bat его скомпилит).
А если нет желания париться, то проще скачать бинари ихние с сорсфоржа.
https://sourceforge.net/projects/boost/files/boost-binaries/

**Comment by VictorVG** [comment]
Ага! Поятно. Посмотрю их скрипты.
