### ISSUE TITLE
По мелочи - косметика в readme_ru.txt и IntChecker2.rc

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#13]
По мелочи, но поправим:

в readme_ru.txt пометим что для Far3 требуется b5354 - раньше то у нас использовались хидеры от b5000, так что вопросы получим.:), и добавим раздел по макросам - по ним есть вопросы, ответим.

и в IntChecker2.rc строка 82 поправим год в копирайте - у нас там сейчас VALUE _"LegalCopyright", "Copyright (C) 2014, Ariman"_, для порядка можно его записать в форме _VALUE "LegalCopyright", "Copyright (C) 2014 - 2919, Ariman"_ (заодно и придиркии снимем :)).

Оба файла с поправками чтобы не делать двойную работу:

[**readme_ru.txt.m4.zip**](https://github.com/lazyhamster/IntChecker/files/2993258/readme_ru.txt.m4.zip)
[**IntChecker2.rc.zip**](https://github.com/lazyhamster/IntChecker/files/2992521/IntChecker2.rc.zip)

P.S.

Добавил в ReadMe раздел 5. по макросам после вопроса [**kraeved**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49572&start=1700#9) на руборде.

**Comment by lazyhamster** [comment]
Закомитил. Доку по макросам я в отдельный файл перенес. А то сильно много букв в readme получается.

**Comment by VictorVG** [comment]
Я так же подумал что для упрощения чтения стоит разделить описание и ТО по макросам. Главное чтобы читали.:)
