### ISSUE TITLE
При использовании плагина Renewal (autoupdate) обновления не происходит.

### ISSUE THREAD

**Issue by alexxis** [lazyhamster/IntChecker#16]
Появляется окно с ошибкой:

- Failed to install the update for the module Integrity Checker. Unable to open input archive stream [0x081] Неверная функция

Версии:

- OS: Win 7 x64
- Far: 3.0.5354 x64
- Far: 3.0.5400 x64
- Renewal (Autoupdate): 3.19.8.4040
- Integrity Checker: 2.7.1

**Comment by lazyhamster** [comment]
А от меня то что надо в данном случае? Архив на плагринге нормальный, открывается как надо. Это надо автора Renewal-а пинать, что там плагину не нравится.

**Comment by alexxis** [comment]
Спасибо за ответ! Ожидал от вас подобную обратную связь. Ok! Вы не при делах, буду пинать другую сторону.

**Comment by alexxis** [comment]
Спасибо, что открестились!.. ;-)

**Comment by alexxis** [comment]
https://sourceforge.net/p/farplugs/tickets/128/#34a4
