### ISSUE TITLE
INFO: Столкнулся с невозможноостью распаковать 64-битный nsis: .../avidem ... mux/ - на деле там QtIFW, а не NSIS.

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#20]
https://forum.farmanager.com/viewtopic.php?p=155793#p155793

> Столкнулся с невозможноостью распаковать 64-битный nsis: https://sourceforge.net/projects/avidem ... mux/2.7.4/
> avidemux_2.7.4_win32.exe - распаковывается нормально, Avidemux_2.7.5 VC++ 64bits .exe - не распаковывается.
> Far30b5465.x64, Observer_x64_1.11.2, msvcp100.dll и msvcr100.dll - x64 10.0.30319.1.
> 7z тоже не может x64-версию распаковать.
> Я правильно понимаю, что nsis-x64 пока не поддерживается? Есть ли планы по добавлению такой поддержки?

там используется не NSIS, а QtIFW - Qt Installer Framework , а для него вообще нет распаковщика. 

И с Avidemux на данный момент всё просто - ветки win32 и win64 в качестве компилятора используют GCC/MinGW и собираются с SDL  посему там более - менее все фильтры что есть в ffmpeg, а инсталлер собирается NSIS, а урезанная по возможностям и набору фильтров ветка vsWin64 собирается в MSVC 2019 с её SDK и как раз там используется QtIFW. 

Я говорил с разработчиком про это и он объяснил, что планирует перевести все платформы на QtIFW для упрощения разработки инсталлятора, но пока хоть две ветки win32 и win64 собираются в GCC и ставятся с помощью NSIS мы имеем её один плюс - на диск не летит ~ 20 Мб стуб QtIFW большую часть объёма которого составляют модули самой Qt нужные ему только для отрисовки UI. Собственно скрипт который он выполняет по сравненю с его объёмом это капля в море, но рюшечки- бантики. :)

**Comment by skipik** [comment]
Это нужно в Observer репортить, а не в IntChecker. :-)

**Comment by lazyhamster** [comment]
Как-то совсем не туда.
