### ISSUE TITLE
Проблема с прерыванием плагина при вызове из цикла. Причина в CheckEsc()

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#23]
Если плагин вызван в цикле Lua скрипта, то из-за текущей реализации CheckEsc() не возможно опросить входную очередь клавиатуры, а следовательно и прервать цикл. Пример прерываемого цикла:
```
local k,l="",0;
for j=1,400000 do
  k = win.ExtractKey();
  if k == "ESCAPE" then break end
  l = l + 1
end
far.Show(k,l,400000)
```
в нём win.ExtractKey() опрашивает входную очередь клавиатуры и если нажата клавиша вовращает её Lua название, и в принципе для прервыания цикла достаточно `if win.ExtractKey() == "ESCAPE" then break end` , но поскольку CheckEsc() перехватывает входную очередь клавиатуры, то нажатие клавиш не доходят до LuaMacro и даже если мы поставим в качестве управляющей клавиши BackSpase (BACK) прервать цикл не удастся - она будет "проигнорирована" циклом вызывая иллюзию ошибки в нём. Это вылезло когда я по просьбе **skipik** добавил в chex() проверку  `if win.ExtractKey() == "ESCAPE" then break end` для прерывания расчёта хэшей в каталогах с большим количеством файлов - если один файл прерывается, то в случае с большим их количеством в качестве брейк-сигнала срабатывает только ESC, остальные не доходят до win.ExtractKey()/win.ExtractKeyEx()/mf.akey(1) и прервать цикл по ним не возможно. 

Я могу конечно сделать экзотику типа прерывания по мышке, но это будет вызывать кучу ошибок при случайном нажатии её клавиш. По идее стоит уточнить CheckEsc() так, чтобы при вызове из макроса по gethash она проверяла входную очередь KBD только во время обработки текущего файла, а после освобождала её позволяя скрипту получить сигнал прерывания цикла. Иначе имеем проблему непрерываемого цикла принуждающего оператора аварийно завершать текущую задачу Far-а - именно это было описано в сообщении **skipik** в мой ПМ на борде.

**Comment by lazyhamster** [comment]
CheckEsc() и так работает в пределах файла, она же только в функции прогресса вызывается. И после окончания обработки файла скрипт может делать с клавиатурой что угодно.
А чтобы цикл не был непрерывный, надо прерывать его когда gethash вернул false вместо хеша.

**Comment by VictorVG** [comment]
В том и проблема, что приходится использовать фильтр чтобы отсечь пустые каталогию Сейчас chex() имеет такой вид:
```
 local function chex(hn,pth,ft,r)
     --
     -- The function for calculating file checksums with support full or relative
     -- UNC paths specified relative to the current panel directory, controlled
     -- recursive processing of directories, partial correction of input errors
     -- for UNC paths and checking the availability of the target object (the user
     -- may not have access rights to it).
     --
     -- User can break processing then pressed ESC keyboard key for files only!
     -- If calculate hashsum for directories break not available by design.
     --
     -- Input parameters:
     --
     -- hn  - is hash algorithm name, string
     -- pth - target UNC path, allays string
     -- ft  - output record format code, integer:
     --       valid value: 0 - GNU (default), 1 - BSD;
     -- r   - recursion flag, string or boolean,
     --        valid value is: true - enable, false or nil - disable (default);
     --
     -- Output:
     --
     -- table included fields by order:
     --
     -- ErrCode    - Error code, integer, value is:
     --               0 - Success, no errors, HashSumm is valid;
     --               1 - Empty folder, recursion is disabled or no files found, HashSumm
     --                   is empty and ObjPath is UNC path;
     --               2 - Target not exist, HashSumm is invalid and d0 is UNC path;
     --               3 - File Access Denied, FileErrCnt greater 0, HashSumm exclude this files;
     -- HashSumm   - calculated hash sum, string, substring separator \n;
     -- ObjPath    - UNC path to object, string;
     -- DirCnt     - scaned directories count, integer;
     -- FileAllCnt - files all count, integer;
     -- FileSucCnt - files success count, integer;
     -- FileErrCnt - files error count, integer;
     --
   local ICId = "E186306E-3B0D-48C1-9668-ED7CF64C0E65";
   local r0,sum0,s0,f0,d0,p,pnt,dc,ec,err,fc,fa = false,"","","","","","",0,0,0,0,0;
   r = tostring(r)
   if r:find("true") then r0 = true elseif r:find("false") then r0 = false else r0 = false end;
   if pth:find("\\$") then p = pth:sub(0,-2) elseif pth:find("/$") then
    p = pth:sub(0,-2) else p = pth end;
    if  ft == 1 then ft = 1 else ft = 0 end;
   if mf.fexist(p) then
    if #mf.fsplit(p,1) == 0 then p = far.ConvertPath(p); pnt = win.GetFileInfo(p).FileName.."\\"; else pnt = "" end
    f0 = win.GetFileInfo(p).FileName
    if not win.GetFileAttr(p):find("d") then
     d0 = p:sub(0, - #f0 - 2);
     fc = 1
     dc = 0
     sum0 = tostring(Plugin.SyncCall(ICId,"gethash",""..hn.."",""..p.."",true));
     if sum0:find("nil") then
      ec = 1
      err = 3
     else
      if ft == 1 then s0 = hn.." ("..f0..") = "..sum0 else s0 = sum0.." *"..f0; end;
      fa = 1
     end;
    else
     local dr,dl,sem = far.GetDirList(p),{},false;
     d0 = p
     dc = #dr;
     for j = 1,#dr do
      dl[j] = dr[j].FileName
      if not win.GetFileAttr(dl[j]):find("d") then
       f0 = dl[j]:sub(#p + 2)
       if r0 then sem = true else if not dl[j]:find("\\",#p + 2) then sem = true else sem = false end end;
       if sem then
        fa = fa + 1
         sum0 = tostring(Plugin.SyncCall(ICId,"gethash",""..hn.."",dl[j],true));
        if sum0:find("nil") then
         ec = ec + 1
         err = math.max(err,3)
        else
         fc = fc + 1
         if ft == 1 then s0 = s0..hn.." ("..pnt..f0..") = "..sum0.."\n" else s0 = s0..sum0.." *"..pnt..f0.."\n" end;
        end
       end
      end;
      if win.ExtractKey()=="ESCAPE" then break end
     end
      if r0 then dc = dc - fa else dc = 0 end
    end
     if #s0 == 0 and r0 then err = math.max(err,1) end
   else
     err = 2
     s0 = ""
     d0 = p
   end
   local ret = { ErrCode = err, HashSumm = mf.trim(s0), ObjPath = d0, DirCnt = dc, FileAllCnt = fa, FileSucCnt = fc, FileErrCnt = ec };
   return ret;
 end;
```
что позволяет нам работать в том числе и с вложенными каталогами и со случами типа "На панели есть  выделенные файлыи каталоги, но надо обработать только файлы в текущем каталоге без учёта рекурсии" и благодаря фильтрации каталогов мы это можем сделать.  Вот сам тестовый скрипт [**test_beta.lua.zip**](https://github.com/lazyhamster/IntChecker/files/3803478/test_beta.lua.zip) . Все возможные настройки документированы в его блоке управления, а он писался для отладки и тестирования chex() в том числе в случае некорректного ввода UNC пути оператором.

**Comment by lazyhamster** [comment]
Ничего не понял. Причем здесь каталоги к проверке выхлопа из gethash?

**Comment by VictorVG** [comment]
Я отсекаю фильтром промежуточные каталоги чтобы добраться до конечного листа дерева и исключить попадание в список nil поскольку для каталога считать хэши не имеет смысла. Сейчас заодно попробовал и  такой вариант тестоввого цикла (если объектов много, то мигом выведет простыню:)):
```
local dr,dl,da,k,l = far.GetDirList(APanel.Path),{},{},"",0;
for j=1,#dr do
  dl[j] = dr[j].FileName
  da[j] = dr[j].FileAttributes
  k = k.."\n"..dl[j].."  "..da[j]
  if win.ExtractKey() == "BACK" then break end
  l = l + 1
end
far.Show(k,l)
```
он сначала выведет список объектов с их атрибутами, а после счётчик всего найденного. И если к примеру распаковать дистрибутивы IntChecker для far3 и ночнушки фара в подкаталоги, а после запустить там скрипт как раз получим простыню под тысячу записей - far.GetDirList() работает очень шустро. Я честно говоря такого не ожидал даже на быстром серверном HDD. Думал успею BackSpace нажать, потянулся к KBD она уже все сделала за доли секунды.:)

**Comment by VictorVG** [comment]
Походу я перестрался с минимизацией чтений с ФС - ведь по идее far.GetDirList() вытаскивает всю запись файла из ФС, а значит вызова win.GetFileAttr() и его косвенных последствий можно избежать, при это появляется шанс сделать цикл прерываемым, а это повод для рефакторинга и устранения ряда не самых приятных видимых последствий её вызова. Попробую, чем чёрт не шутит покуда Бог спит?:)

**Comment by shmuz** [comment]
@lazyhamster , предлагаю в случае прерывания вычисления пользователем возвращать строку "Esc" вместо предыдущего вычисленного хэша (что имеет место сейчас на версии 2.7.2.0). Тогда макрос сможет узнать, что пользователь прервал вычисление и предпринять соответствующие действия.

**Comment by lazyhamster** [comment]
> вместо предыдущего вычисленного хэша (что имеет место сейчас на версии 2.7.2.0).

Это поведение уже исправлено в 2.7.3 (был даже релиз). Теперь возвращается false, если ошибка или юзер прервал выполнение. Точнее, это Фар по умолчанию туда false сует, я просто NULL возвращаю в OpenW,

**Comment by shmuz** [comment]
> Это поведение уже исправлено в 2.7.3

ОК, я этого не знал. Но это не меняет моего предложения - возвращать "Esc" в случае прерывания пользователем.

**Comment by VictorVG** [comment]
@lazyhamster

Кстати по мне это даже удобнее чтобы если плагин прочитал из очереди ESC, то он бы передал его на выход макросу либо если это возможно (идеальный случай) пометил это сообщение в очереди KBD как не прочтённое. 

Поскольку если я правильно понял, то сейчас если кто-то читаем сообщение, ОС помечает его "прочтено" и удаляет из очереди. 

Примерно сходно работала система сообщений в ядре OS/3360 - OS/370 - если сообщение прочтено то оно немедленно удалялось из неё.

chex() я переделаю - есть идея как уменьшить число операций чтения с диска и заодно постараюсь сделать цикл прерываемым. Тут мне нужно чтобы было что читать из очереди KBD.

**Comment by shmuz** [comment]
@VictorVG , если автор реализует моё предложение (а реализация его крайне простая), то макросу вообще не надо будет иметь дело с чтением клавиатуры.

**Comment by VictorVG** [comment]
Это хорошо, ноя думаю что всё одно мне стоит уменьшить число операций обращения к дискам за счёт считывания массива win.GetDirList() и работы с ним не только по срезу FileNames, но и FileAttributes. Я вот только хочу для себя уточнить - её возврат nil на одиночный файл можно ли рассматривать как признак что если объект существует, то это файл, а значит можно строить на этом ответе детектор. Если это не имеет смысла, то есть win.GetFileInfo, но она в поле FileNames возвращает только имя файла и приходится проверять что где файл находится по отношению к текущему каталогу. Идея с эта смутная, но похоже позволит реализовать ряд новых полезных возможностей для плагина, а раз так, то мне стоит с ней повозится.

**Comment by VictorVG** [comment]
С учётом подсказанного и вылезшей бяки старого детектора - он выводил nil на корневой каталог шары, поправил chex() заодно с небольшим рефакторингом и сохранением всех её возможностей. Прерывается, но файлы работает нажатие Esc, а на каталоги придётся несколько раз давить Backspace. Проверял и на локальных каталогах и на серверной щаре //SERVER/share/ - прерываемся , даже когда на NFS под Salaris на SPARC Server стоящим у чёрта на рогах и с каналом Frame Relay 512 Kb/s где было около 200 тыс. файлов. Пришлось подождать, но счётчик показал всего 129 файлов и 15 каталогов из всей кучи. Esc для каталогов не прошёл, ну по BS промахнуться сложно.:)

Вот что вышло - только сама chex():

```
 local function chex(hn,pth,ft,r)
     --
     -- The function for calculating file checksums with support full or relative
     -- UNC paths specified relative to the current panel directory, controlled
     -- recursive processing of directories, partial correction of input errors
     -- for UNC paths and checking the availability of the target object (the user
     -- may not have access rights to it).
     --
     -- User can break processing then pressed ESC keyboard key for files only!
     -- If calculate hashsum for directories break not available by design.
     --
     -- Input parameters:
     --
     -- hn  - is hash algorithm name, string
     -- pth - target UNC path, allays string
     -- ft  - output record format code, integer:
     --       valid value: 0 - GNU (default), 1 - BSD;
     -- r   - recursion flag, string or boolean,
     --        valid value is: true - enable, false or nil - disable (default);
     --
     -- Output:
     --
     -- table included fields by order:
     --
     -- ErrCode    - Error code, integer, value is:
     --               0 - Success, no errors, HashSumm is valid;
     --               1 - Empty folder, recursion is disabled or no files found, HashSumm
     --                   is empty and ObjPath is UNC path;
     --               2 - Target not exist, HashSumm is invalid and d0 is UNC path;
     --               3 - File Access Denied, FileErrCnt greater 0, HashSumm exclude this files;
     -- HashSumm   - calculated hash sum, string, substring separator \n;
     -- ObjPath    - UNC path to object, string;
     -- DirCnt     - scaned directories count, integer;
     -- FileAllCnt - files all count, integer;
     -- FileSucCnt - files success count, integer;
     -- FileErrCnt - files error count, integer;
     --
   local ICId = "E186306E-3B0D-48C1-9668-ED7CF64C0E65";
   local r0,sum0,s0,f0,d0,p,pnt,dc,ec,err,fc,fa = false,"","","","","","",0,0,0,0,0;
   r = tostring(r)
   if r:find("true") then r0 = true elseif r:find("false") then r0 = false else r0 = false end;
   if pth:find("\\$") then p = pth:sub(0,-2) elseif pth:find("/$") then
    p = pth:sub(0,-2) else p = pth end;
    if  ft == 1 then ft = 1 else ft = 0 end;
   if mf.fexist(p) then
    if #mf.fsplit(p,1) == 0 then p = far.ConvertPath(p); pnt = win.GetFileInfo(p).FileName.."\\"; else pnt = "" end
    f0 = win.GetFileInfo(p).FileName
    if not win.GetFileInfo(p).FileAttributes:find("d") then
     d0 = p:sub(0, - #f0 - 2);
     fc = 1
     dc = 0
     sum0 = tostring(Plugin.SyncCall(ICId,"gethash",""..hn.."",""..p.."",true));
     if sum0:find("nil") then
      ec = 1
      err = 3
     else
      if ft == 1 then s0 = hn.." ("..f0..") = "..sum0 else s0 = sum0.." *"..f0; end;
      fa = 1
     end;
    else
     local dr,da,dn,sem = far.GetDirList(p),{},{},false;
     d0 = p
     dc = #dr;
     for j = 1,#dr do
      if win.ExtractKey()=="BACK" then break end
      da[j] = dr[j].FileAttributes
      dn[j] = dr[j].FileName
      if not da[j]:find("d") then
       f0 = dn[j]:sub(#p + 2)
       if r0 then sem = true else if not dn[j]:find("\\",#p + 2) then sem = true else sem = false end end;
       if sem then
        fa = fa + 1
         sum0 = tostring(Plugin.SyncCall(ICId,"gethash",""..hn.."",dn[j],true));
        if sum0:find("nil") then
         ec = ec + 1
         err = math.max(err,3)
        else
         fc = fc + 1
         if ft == 1 then s0 = s0..hn.." ("..pnt..f0..") = "..sum0.."\n" else s0 = s0..sum0.." *"..pnt..f0.."\n" end;
        end
       end
      end;
      if win.ExtractKey()=="BACK" then break end
     end
      if r0 then dc = dc - fa else dc = 0 end
    end
     if #s0 == 0 and r0 then err = math.max(err,1) end
   else
     err = 2
     s0 = ""
     d0 = p
   end
   local ret = { ErrCode = err, HashSumm = mf.trim(s0), ObjPath = d0, DirCnt = dc, FileAllCnt = fa, FileSucCnt = fc, FileErrCnt = ec };
   return ret;
 end;
```
а тест отдельно - [**test_beta.lua.zip**](https://github.com/lazyhamster/IntChecker/files/3806640/test_beta.lua.zip)

**Comment by VictorVG** [comment]
С новой версией chex() прервать счёт удаётся, корневой каталог считается допустимым UNC путём (в превичной задумке этот вариант не рассматривался):

![1](https://user-images.githubusercontent.com/906886/68180053-44c4a180-ffa3-11e9-8d44-ee959f9542c1.png)

но, приходится подождать момента прохождения сигнала прерывания счёта - похоже при обработке каталогов возникает задержка, видимо в CheckEsc().

**Comment by VictorVG** [comment]
@lazyhamster 
@shmuz 

Вообще-то по раздумью в случае прерывания пользователем плагину надо возвращать ESC так как сейчас механизм возникновения проблемы комплексный, и я предлагаю идти от модели "чёрного ящика" - считать ЭВМ "чёрным ящиком" (ЧЯ) с известным набором входных сигналов и реакций на них, а так же состояний (S(j)), а само её устройство игнорировать. Там проще анализировать.

В момент времени Т(0) на вход ЧЯ поступает импульсный сигнал прерывания, и с задержкой t обрабатывается, при этом ЧЯ выводит свои сигналы управления на выход к которому подключён управляемый клиентом переключатель который тот может монопольно заблокировать . К переключателю ЧЯ подключены два автомата А1 и А2 с наборами свойств:

1 .А1 если не пришёл сигнал break выполняет задание или простаивает. Если поступил break, то по его фронту выполняемое задание прерывается.

2. А2 организует циклический запуск А1, читает сигналы управления с ЧЯ, если  поступил break то по его фронту прерывает цикл.

Запустились, в момент времени T(0), А2 запустил А1 и ждёт пока тот отработает. В момент времени Т(1) из ЧЯ пришёл break, А1 прервался, но А2 про break ничего не знает - он пришёл на А1 и перезапускает его. И если в это время снова поступит break он попадёт в А1, но вероятность что он попадёт в А2 стремится к нулю потому, что А1 и А2 срабатывают на фронт break т.е. переход 10 или 01, а вероятность того, что данное событие произойдёт до того, как А2 снова запустит А1 случайна, а потому в подавляющем большинстве опытов с посылкой break мы будем наблюдать, что А1 прерывается, а после работает далее до конца цикла и прервать его нам не удасться...

**Comment by VictorVG** [comment]
А в совсем общем виде всё вышесказанное можно свести к такой модели:

Есть некий вход с переключателем на два выхода, и пара подключённых к ним автоматов, первый управляет вторым запуская его в некоем цикле, тот на время работы переключает вход на себя. Прервать цикл можно, но только в том случае если команда стоп попадёт во второй автомат, но из-за освойств данной системы вероятность такого события стремится к нулю.

Вопрос как прервать цикл досрочно?

P.S.

Вариант с обработкой nil прикинул - там вылезет вторая неопределённость: что породило nil - ошибка в расчёте/Access Deined или оператор нажал ESC. Проверяемо, но с гарантированой руганью от пользователей которые лишних запросов на дух не переносят.

**Comment by VictorVG** [comment]
Как я и предполагал если плагин зовём в цикле вероятность поймать тот момент времени когда скрипт может получить ESC близка к нулю, зато Backspace ловится уверено. Потому пока оставлю вариант с ним, правда добавил ещё один код ошибки - 4 - юзер нажал брейк хоткей и несколько ужесточил формальные параметры - Recursion только boolean. 

Сейчас все переделки идут в скрипте-оболочке вызывающем chex() - там переписывается логика управления так, чтобы минимизировать число запросов к пользователю и влияние его  ошибок при вводе команд.

**Comment by lazyhamster** [comment]
Добавил вывод строки "userabort" вместо false, если юзер прервал операцию в gethash.

**Comment by VictorVG** [comment]
Отлично!  Сейчас её использую так это сразу позволяет решить задачу однозначности диагностики.

**Comment by VictorVG** [comment]
В Git 4ccaf0dadfb268b55dfd7b1a22b5b0f1c8085e5c проблема прерываемости цикла решена, потому в chex() потребовались минимальные изменения:
```
 local function chex(hn,pth,ft,r)
     --
     -- The function for calculating file checksums with support full or relative
     -- UNC paths specified relative to the current panel directory, controlled
     -- recursive processing of directories, partial correction of input errors
     -- for UNC paths and checking the availability of the target object (the user
     -- may not have access rights to it).
     --
     -- User can break calculation if pressed ESC key then returned ErrCode = 4.
     --
     -- Input parameters:
     --
     -- hn  - is hash algorithm name, string
     -- pth - target UNC path, allays string
     -- ft  - output record format code, integer:
     --       valid value: 0 - GNU (default), 1 - BSD;
     -- r   - recursion flag, string or boolean,
     --        valid value is: true - enable, false or nil - disable (default);
     --
     -- Output:
     --
     -- table included fields by order:
     --
     -- ErrCode    - Error code, integer, value is:
     --               0 - Success, no errors, HashSumm is valid;
     --               1 - Empty folder, recursion is disabled or no files found, HashSumm
     --                   is empty and ObjPath is UNC path;
     --               2 - Target not exist, HashSumm is invalid and d0 is UNC path;
     --               3 - File Access Denied, FileErrCnt greater 0, HashSumm exclude this files;
     --               4 - User abort, FileSucCnt is valid, DirCnt is wrong, HashSum does not include canceled files.
     -- HashSumm   - calculated hash sum, string, substring separator \n;
     -- ObjPath    - UNC path to object, string;
     -- DirCnt     - scaned directories count, integer;
     -- FileAllCnt - files all count, integer;
     -- FileSucCnt - files success count, integer;
     -- FileErrCnt - files error count, integer;
     --
   local ICId = "E186306E-3B0D-48C1-9668-ED7CF64C0E65";
   local r0,sum0,s0,f0,d0,p,pnt,dc,ec,err,fc,fa,det = false,"","","","","","",0,0,0,0,0;
   r = tostring(r)
   if r:find("true") then r0 = true elseif r:find("false") then r0 = false else r0 = false end;
   if pth:find("\\$") then p = pth:sub(0,-2) elseif pth:find("/$") then
    p = pth:sub(0,-2) else p = pth end;
    if  ft == 1 then ft = 1 else ft = 0 end;
   if mf.fexist(p) then
    if #mf.fsplit(p,1) == 0 then p = far.ConvertPath(p); pnt = win.GetFileInfo(p).FileName.."\\"; else pnt = "" end
    local dr,da,dn = far.GetDirList(p),{},{};
    if #dr == 0 then
     f0 = win.GetFileInfo(p).FileName
     d0 = p:sub(0, - #f0 - 2);
     fc = 1
     dc = 0
     sum0 = tostring(Plugin.SyncCall(ICId,"gethash",""..hn.."",""..p.."",true));
     if sum0:find("nil") then
      ec = 1
      err = 3
     elseif sum0:find("userabort") then
      ec = 1
      err = 4
     else
      if ft == 1 then s0 = hn.." ("..f0..") = "..sum0 else s0 = sum0.." *"..f0; end;
      fa = 1
     end;
    else
     local sem = false;
     d0 = p
     dc = #dr;
     for j = 1,#dr do
      da[j] = dr[j].FileAttributes
      dn[j] = dr[j].FileName
      if not da[j]:find("d") then
       f0 = dn[j]:sub(#p + 2)
       if r0 then sem = true else if not dn[j]:find("\\",#p + 2) then sem = true else sem = false end end;
       if sem then
        fa = fa + 1
         sum0 = tostring(Plugin.SyncCall(ICId,"gethash",""..hn.."",dn[j],true));
        if sum0 == "userabort" then
         ec = ec + 1
         err = math.max(err,4)
         break
        elseif sum0 == "nil" then
         ec = ec + 1
         err = math.max(err,3)
        else
         fc = fc + 1
         if ft == 1 then s0 = s0..hn.." ("..pnt..f0..") = "..sum0.."\n" else s0 = s0..sum0.." *"..pnt..f0.."\n" end;
        end
       end
      end;
     end
      if r0 then dc = dc - fa else dc = 0 end
    end
     if #s0 == 0 and r0 then err = math.max(err,1) end
   else
     err = 2
     s0 = ""
     d0 = p
   end
   local ret = { ErrCode = err, HashSumm = mf.trim(s0), ObjPath = d0, DirCnt = dc, FileAllCnt = fa, FileSucCnt = fc, FileErrCnt = ec };
   return ret;
 end;
```
я туда добавил унифицированные обработчики кода возврата _useraborted_ чтобы люди не думали "А что нажимать?" т.к. ESС, интуитивно оначчает "Прервать, отменить", м ставлю код ошибки 4 не включая в HashSum отмененные файлы.

Этого я считаю достаточно, и данный инц можем закрыть. А я кроме IntChecker.Run.Lua поправлю документацию описав возможность прерывания цикла, и в демо-скрипт соответствующий пример добавлю поскольку chex() на такую роль не годится.

**Comment by lazyhamster** [comment]
Тогда закрываем.

**Comment by VictorVG** [comment]
Обещанная демка:
```
-- Demo скрипт для вызова плагина
--
-- Параметры вызова: "команда", "алгоритм", "путь к файлу"
-- Поока поддерживается одна команда "gethash" - получить хеш одного файла
--
-- Список доступных алгоритмов:
-- crc32, md5, sha1, sha-256, sha-512, sha3-512, whirlpool
--
-- Регистр в названии команд и в названии алгоритмов не учитывается.
--
-- Плагин возвращает рассчитанный хеш файла, сообщения об ошибках отключены
-- заданием параметра Quiet = true.
--
-- Пользователь может прервать вычисления нажав ESC и подтвердив отмену операции
-- в диалоге плагина.


-- Пример вызова плагина для файла под курсором на активной панели

Macro {
  description="Calculate hash for the file under the cursor";
  area="Shell";
  key="CtrlShiftH";
  action=function()
  local Quiet,ICID = true,"E186306E-3B0D-48C1-9668-ED7CF64C0E65";
  far.Show (Plugin.SyncCall(ICID,"gethash","md5",APanel.Path0.."\\"..APanel.Current,Quiet))
  end;
}

-- Пример вызова плагина в прерываемом цикле для текущего каталога на активной панели

Macro {
  description="Calculate hash for current folder";
  area="Shell";
  key="AltShiftH";
  action=function()
  local Quiet,ICID,s0,sum = true,"E186306E-3B0D-48C1-9668-ED7CF64C0E65","","";
  for j=1,APanel.ItemCount do
   s0 = Plugin.SyncCall(ICID,"gethash","md5",Panel.Item(0,j,0),Quiet)
   if s0 == "userabort" then
    far.Show ("User press ESC button, all next operations is canceled.")
    break
   else
    sum = sum.."\n"..tostring(s0)
   end
  end;
   far.Show(sum)
 end
}
```
- её можно сразу использовать благо в ней ломаться нечему.:)
