### ISSUE TITLE
Недостаток в реализации Plugin.Call() плагина - функция не обрабатывает симлинки

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#25]
В текущей версии плагина не обрабатываются симлинки что легко проверяется:

1) берём любой файл и создаём на него симлинк;

2) выполняем команду

`lua:far.Show(Plugin.SyncCall("E186306E-3B0D-48C1-9668-ED7CF64C0E65","gethash","SHA-256",APanel.Current,true))` 

сначала для файла и после для симлинка на него.

В случае файла плагин выведет хэш, в случае симлинка увидим _false_, но если вызвать плагин  для симлинка из меню плагинов (по F11 или через Plugin.Menu()), то плагин перейдёт по симлинку и просчитает хэш для его целевого файла.

Я задал вопрос **shmuz** на [**ру-борде**](https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=280#20):

> вопрос - с чем я встретился: ограничением плагина или это макродвижок не обрабатывает симлинки?

и получил ответ:

> **Victor_VG**  
> 
> "Собственно отсюда и вопрос - с чем я встретился: ограничением плагина или это макродвижок не обрабатывает симлинки?"
> 
>   Это недоработка в плагине: плагин по-разному обрабатывает имя файла при вызове из меню и при вызове из макроса.

Потому в новой версии chex() v2.0 (она основана на более быстрой far.RecursiveSearch()  и имеет улучшенную диагностику ошибок) временно заблокировал обработку силинков, но если она будет реализована в плагине, для её включения будет достаточно убрать пару проверок и не выводить код возврата 6 (симлинк). Новый IntChecker.Run.lua v2.0 будет реализован на chex() v2.0 - я сейчас адаптирую к ней обработку возврщаемой ей таблицы - в ней осталось пять полей вместо семи: поля ObjPath и DirCnt убраны за ненужностью т.к. far.RecursiveSearch() сама отфильтровывает каталоги. Хотя функция стала большей по числу строк - 83 против 60, но в целом работает быстрее версии 1.0.

**Comment by lazyhamster** [comment]
Исправлено в e09c8fc22ccfb04c6288192f6f773f781b2d84bc

**Comment by VictorVG** [comment]
Отлично! Сейчас Process Hacker v3.0.7470.2943 Git-30046a37 соберётся и наше посмотрим. У меня в chex() стоят комментарии тем где нужно убрать проверки - зачем вспоминать где чистить?

**Comment by VictorVG** [comment]
Собрал, проверил, работает. Закрываю, дальше моя возня с chex() и скриптами.
