### ISSUE TITLE
Нужна адаптация к изменениям b5788/b5801 иначе портится вывод в диалоге параметров

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#30]
Получил письмо с отчётом об ошибке:

> От:    **MXPHunter**
> Дата:    00:17 24-05-2021
> Тема:    визуальный баг FAR 5800 + IntChecker2 2.8.0
> 
> Обновил FAR до 5800 и начало дурить меню плагина IntChecker2 версии 2.8.0
> Конкретно меню генерации хешей / Output to - Single file и далее вниз закрас цветом меню
> 
> ![ic](https://user-images.githubusercontent.com/906886/119368559-d1d16780-bcbb-11eb-8cdd-eea1f5e8e963.png)

и у меня,  если взять набор с заведом чистым профилем 

на b5787 ещё нет:

![b5787_ic](https://user-images.githubusercontent.com/906886/119368757-13faa900-bcbc-11eb-9c72-2af18071513a.png)

но уже с b5788 воспроизодится:

![b6788_ic](https://user-images.githubusercontent.com/906886/119368798-1f4dd480-bcbc-11eb-90a4-ed606dcd521d.png)

и немного позднее:

> Меню то самое. Сейчас проверил на 5802 поведение не изменилось. Background пункта Общий файл залезает на пункты до Экран включительно

изменения были внесены в b5788 Git-15646640d, дальше можно не проверять, но похоже стоит смотреть в сторону эксперимента 

> drkns 02.05.2021 11:28:04 +0100 - build 5788
> 
> 1. Experimental: editor selection color can have transparent foreground/background.
> 
> 2. More transparency to come: make sure you fill alpha channels in FarColor structures properly in API.
> 
> _2. Multiple fixes related to color merging and processing._

третьего пункта - смешение цветов (?) у нас вроде нет ничего. Я пробовал собрать с новыми хидерами и глянуть что будет - нужна адаптация под изменившиеся в b5788  структуры диалога иначе бинарник не собирается....

**Comment by VictorVG** [comment]
Сейчас у себя сравнил три разных запущенных копии. Слева направо:- b5797 и b5802 распакованы в новый каталог, профиля нет, b5802 рабочая копия. Специально поместил все три рядом чтобы было видно что меня ставит в тупик - визуальные артефакты в меню выбора _Вывод в/на_  : 

![compare](https://user-images.githubusercontent.com/906886/119412705-fa298800-bcf4-11eb-8a60-b88dc73ed4ac.png)

**Comment by VictorVG** [comment]
По словам **DrKnS** в [**GH#406**](https://github.com/FarGroup/FarManager/issues/406) ошибка находится в [**Far3.cpp strings 676 - 679**](https://github.com/lazyhamster/IntChecker/blob/e2a068a6afa6b64a923b5f5e3342c604e7605aa3/source/IntChecker2-Far3.cpp#L676-L679).

**Comment by VictorVG** [comment]
Спасибо что **ctapmex** подсказал как поправить:

_Fix by ctapmex (Aleksey Dobrunov) for b5788+_

```
--- ./source/IntChecker2-Far3.cpp	Git 4eeb3ce
+++ ./source/IntChecker2-Far3.cpp	workingcopy
@@ -677,6 +677,7 @@
 	editFileName->Flags = DIF_EDITEXPAND|DIF_EDITPATH|DIF_FOCUS;
 	editFileName->X1 += 2;
 	editFileName->Y1 -= 3;
+	editFileName->Y2 =editFileName->Y1;
 	
 	dlgBuilder.AddSeparator();
 	dlgBuilder.AddCheckbox(MSG_GEN_RECURSE, &doRecurse, 0, false);

```
уже проверил - ОК!, правда версию пока менять не стал, хотя по идее и стоит, но может что ещё попадёт под изменения, так сразу и патч учесть, а пока работает - ломать не будем.:)

**Comment by VictorVG** [comment]
Решился - поднял ревизую до 1 - версия 2.8.1 чтобы не путать исправленный и релизный бинарники:

./source/version.m4i
```
m4_define(VMAJOR,    `2')m4_dnl
m4_define(VMINOR,    `8')m4_dnl
m4_define(VREVISION, `1')m4_dnl
m4_define(PLUGIN_VERSION, `VMAJOR.VMINOR.VREVISION')m4_dnl

```
и в доках пометил:

[history_en.txt](https://github.com/lazyhamster/IntChecker/files/6584070/history_en.txt)

[history_ru.txt](https://github.com/lazyhamster/IntChecker/files/6584071/history_ru.txt)

**Comment by lazyhamster** [comment]
Добавил патч в исходники.

**Comment by VictorVG** [comment]
Отлично! Я уже по логам увидел изменения, но и колорер 1.3.26 поймал что тот падает или на HTML если там длинная строка, или на логах Гит. Надо отписать, но хочу сначала сам посмотреть где поскольку full.mdmp выходят слишком габаритные - сначала 517 Мб, второй раз 318 Мб. Придётся по мини дампу глядеть, а после Алексею расказать что я обнаружил благо и повод и желание глянуть имеются. Можно новую версию использовать, но для себя одно, а в проекте - тогда убирать поддержку ОС ниже семёрки, но пока никто ни за ни против у меня не отписался....
