### ISSUE TITLE
Prevent computer from hibernation

### ISSUE THREAD

**Issue by ujos** [lazyhamster/IntChecker#37]
There is a folder with many images and videos. It takes ~30 minutes to calculate the hashes for all the files. Would be great if plugin prevents computer from being sleep while working on checksum calculation. 

Following is a code snippet that does the job:

```cpp
// Enable away mode and prevent the sleep idle time-out.
//
SetThreadExecutionState(ES_CONTINUOUS | ES_SYSTEM_REQUIRED | ES_AWAYMODE_REQUIRED);

PerformChecksumCalcualtion();

//
// Clear EXECUTION_STATE flags to disable away mode and allow the system to idle to sleep normally.
//
SetThreadExecutionState(ES_CONTINUOUS);
```

**Comment by lazyhamster** [comment]
Makes sense. I'll look into adding this feature.

**Comment by lazyhamster** [comment]
Added in b5457fcc8fe88023fa53b95a32fc3f64449d5a1e
