### ISSUE TITLE
Нет бинарных сборок для стабильных версий FAR3

### ISSUE THREAD

**Issue by greyleo** [lazyhamster/IntChecker#4]
Спасибо Вам за полезный плагин, но пользоваться не получается из-за отсутствия сборок для текущей версии .4949
Сделайте, пожалуйста.

**Comment by lazyhamster** [comment]
Для стабильных сборок версии не будет. В 4964 был фикс, на который расчитывает плагин для правильной работы.
Актуальные сборки это не страшно, можно свободно пользоваться :)
