### ISSUE TITLE
v2.8.2 - сломалась проверка BSD хэшей

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#43]
Проверка простейшая берём пару хэшфайлов - один в формате GNU, а второй в формате BSD UNIX. Например (на нём и обнаружил ошибку) скачиваем с Oracla JDK 20.0.2 for Windows (~ 160MB):
```
curl -C - -LRZO https://download.oracle.com/java/20/archive/jdk-20.0.2_windows-x64_bin.exe
curl -C - -LRZO https://download.oracle.com/java/20/latest/jdk-20_windows-x64_bin.exe.sha256
```
правим:

формат BSD:

`SHA-256 (jdk-20.0.2_windows-x64_bin.exe) = ef40941f1b54b52747d98330ca845374bccb8e3635fc7f647f60405cf51eb17f`

формат GNU:

`ef40941f1b54b52747d98330ca845374bccb8e3635fc7f647f60405cf51eb17f *jdk-20.0.2_windows-x64_bin.exe`

и запускаем проверку. 

Результат:

Файл в формате GNU распознаётся любой версией плагина, а файл в формате BSD не распознаётся версией 2.8.2 - 2.8.3 Git e0cf730 - они выводят сообщение "_Файл не является списком хешей_".

Файлы-примеры приложены - [**examples.zip**](https://github.com/lazyhamster/IntChecker/files/12090614/examples.zip)

cURL скачал файл без ошибок - проверено по его SHA-256, да и сам JDK установился на сети.

P.S.

Я уже было решил скриптом костылить, но стоит ли?

**Comment by VictorVG** [comment]
Отбой - это мне нужно чуток IntChecker.Run.lua поправить. Сейчас сделаю и выложу. Заоодно ви текстовке опечатки приберу - попадались на глаза, значит вычитаю.

**Comment by VictorVG** [comment]
Готово - https://github.com/VictorVG/Source/releases/tag/icr201

дифф:

[git_diff.txt](https://github.com/lazyhamster/IntChecker/files/12091811/git_diff.txt)

**Comment by lazyhamster** [comment]
В BSD формате имя хеша без дефиса пишется

`SHA256 (jdk-20.0.2_windows-x64_bin.exe) = ef40941f1b54b52747d98330ca845374bccb8e3635fc7f647f60405cf51eb17f`

В более старых версиях плагина как раз неправильно это парсилось.

**Comment by VictorVG** [comment]
Там ещё по мелочи - опечатки в script-docs.txt - https://github.com/VictorVG/Source/releases/tag/icr201u . Сюда же добавил [script-docs.txt](https://github.com/lazyhamster/IntChecker/files/12092099/script-docs.txt) исправленный вариант. Упусил их вначале, хотя помнил что где-то есть.:)

**Comment by VictorVG** [comment]
Это я заметил и поправил, ну и чуток идей появилось. И, хотя не по теме, но выплыло - проволокли с испытаний почти 670000 файлов приборных логов объёмом под 49 Тб и их нужно проверить на дубликаты. Сранение по SHA1 пропустило около полусотни дубликатов. Пришлось создавать общий хэш в SHA256, сортировать его, а потом убирать отловленные дубликаты т.к. анализ иного лога может и пару недель отнять. 

Потому, убедился, что возможность сравнения каталогов по SHA256 как в версии до 2.8.0 включительно всё-таки работает пусть и медленнее, но не дает ошибок т.к. для SHA1 вероятность коллизии алгоритма ~ 6*10E-6, а для SHA256 условия её возникновения вроде пока не найдены.
