### ISSUE TITLE
Не работает опция [x] Save hashes in uppercase

### ISSUE THREAD

**Issue by greyleo** [lazyhamster/IntChecker#5]
Ставишь, снимаешь галку - всё равно мелкими буквами...

**Comment by lazyhamster** [comment]
Какая версия плагина и фара? У меня не повторяется.

**Comment by greyleo** [comment]
3,0,4980 х64
2,6,1

**Comment by lazyhamster** [comment]
И правда, не работает. Как то я затупил, не на той версии проверил.
Спасибо за информацию, исправлено.
