### ISSUE TITLE
Wishes: по возможности добавить BSD формат записи хэшей

### ISSUE THREAD

**Issue by VictorVG** [lazyhamster/IntChecker#7]
На серверах проектов ОС семейства BSD UNIX используется такой формат строки хэша:

_алгоритм_ (_имя_файла_) = _значение_хеша_

например [**OpenBSD 6.2 Instrall CD**](https://mirrors.pidginhost.com/pub/OpenBSD/6.2/amd64/SHA256):

_SHA256 (install62.iso) = b7994d29c7db3087db65158901d700fb7d10500b9b7496c1d86b285cabce0a2b_

, на проекте FreeBSD.org формат записи аналогичен. Для примера возьмём любую строку из ftp://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/11.1/CHECKSUM.SHA256-FreeBSD-11.1-RELEASE-amd64 или ftp://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/11.1/CHECKSUM.SHA512-FreeBSD-11.1-RELEASE-amd64 :

_SHA256 (FreeBSD-11.1-RELEASE-amd64-bootonly.iso) = ab1539894e74aef77c1c4729fbd2362fc3bd30b71f24db68e1b0307723b72752_

_SHA512 (FreeBSD-11.1-RELEASE-amd64-bootonly.iso) = aa5891b9ab0bd2a1c13fdffd3ab80998f3d17bc54afeae0c183cf286d746f9b5eb8e1bd6b1a5598aeb36419fd1ca0becfa02d3f9854f382b1d7ad0cc2423f47f_

В случае неудачи распознование формата строки хэща имеет смысл выводить сообщение не в общем виде "_Файл ... не является допустимым списком хэшей_", а более понятно - "_Формат строки хэша не распознан_" - так проще ориентироваться в причинах пробемы...

**Comment by lazyhamster** [comment]
> На серверах проектов ОС семейства BSD UNIX используется такой формат строки хэша:
BSD формат поддерживается в режиме чтения.

> В случае неудачи распознование формата строки хэща имеет смысл выводить сообщение не в общем виде
Формат может быть и распознан, а файл содержать ещё какой-то мусор. Отлуп идет именно на уровне всего файла.

**Comment by VictorVG** [comment]
Жаль. В БСД-хтолько такие записи есть. Иныхсервер не пропустит.

**Comment by lazyhamster** [comment]
В смысле? Тебе их надо создавать и отправлять куда-то?

**Comment by VictorVG** [comment]
Образы проверять, да и создавать приходтся. Не всегда есть под рукой живой демон, а когда пишу скрипты обновления туда летят сотни пакеджей, а в них сейчас внутри по другому сделано  - в тарбалле упакованом xz лежат два манифеста +COMPACT_MANIFEST и +MANIFEST и в первом из них хэши сорцов, а целостность самого тарбалла не проверить. Вот посмотри живьём - 
[curl-7.52.1_1.txz.zip](https://github.com/lazyhamster/IntChecker/files/1474780/curl-7.52.1_1.txz.zip) (этот не большой, иные по сотне Мб есть. На старых было проще проверять - в +MANIFEST в дереве стояли SHA-256 для модулей можно было бегло проверить . Вот один сохранился 
[a2ps-a4-4.13b_4.txz.zip](https://github.com/lazyhamste r/IntChecker/files/1474804/a2ps-a4-4.13b_4.txz.zip) или в +CONTENTS смотрел MD5 там она в дереве указывалась:

lib/xpi/langpack-ca@seamonkey.mozilla.org/chrome/ca/locale/ca/communicator/help/glossary.xhtml
@comment MD5:2950f142440a4cdc5aed47283239c936

ей-ей, проще было.:)

**Comment by VictorVG** [comment]
В принципе на уровне одиночного файла задача решена в IntChecker.Run.lua v1.4.2. Осталось только придумать как распространить данное решение на список файлов. Это дело записал в [**ToDo**](https://github.com/VictorVG/PLG/wiki/ToDo) на "когда понадобится".

**Comment by VictorVG** [comment]
Ну, кое что я уже затеял - начал возится с реализацией пункта 1. _ToDo - TASK: IntChecker.Run.lua - create multi string BSD format hash file for file list or directory tree. STATUS: Not started, priority - very low, wait_ и вылезли интересные фокусыс очисткой буфера обмена Far . Можно посмотреть что произойдёт запустив lua:test.lua и приаттаченного архива [test.lua.zip](https://github.com/lazyhamster/IntChecker/files/3666584/test.lua.zip). Ну, попробую через переменную-накопитель решить задачку. Не хочу возится с таблицами и массивами в Lua. Это не PL/1 с его возможностью работать со вложенными многомерными массивами на уровне вложенности до 63. Там это просто - _Declare A(i,j,k( arry 0_ всё, трёхмерный массив переменного размера объявлен и инициализирован нулями.:)

**Comment by VictorVG** [comment]
Ну, я тут по ходу пьесы нам демку накропал:
```
local function mkhash(hn,pt)
-- Функция не работает с виртуальными панелями и каталогами плагинов!
-- Возвращает посчитанный хэш или 0 при ошибке, или -1 если файл на
-- виртуальной панели плагина, каталоги пропускаются;
-- pt - UNC путь к проверяемому файлу;
-- hn - имя алгоритма;
local ICId,h,p="E186306E-3B0D-48C1-9668-ED7CF64C0E65",hn,pt;
 if not APanel.Root then 
  if not APanel.Folder then
   if APanel.Plugin then do return -1 end
     else do return mf.string(Plugin.SyncCall(ICId,"gethash",""..h.."",""..p.."")) end
   end;
  end;
 end;
end;
far.Show("IntChecker2 demo. SHA-256 summ for \""..APanel.Current.."\"\n",mkhash("SHA-256",APanel.Current));
```
а то как-то IntChecker.GetFileHash.lua вроде и хорошь, но там макрос, а значит ставить, а тут lua:@IntChecker.Macro.Example.lua и любуйся картинкой. Что от демки и требуется.:) Приаттачил готовую:  [**IntChecker.Macro.Example.lua.zip**](https://github.com/lazyhamster/IntChecker/files/3678689/IntChecker.Macro.Example.lua.zip)

**Comment by VictorVG** [comment]
Новая версия в IntChecker.Run.lua v1.5.0 #18, а закоммитим  и их оба можно закрывать - задачи ТоДо выполнены.:)
